/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SupplyStatusRouteImport } from './routes/supply-status'
import { Route as StockMovementsRouteImport } from './routes/stock-movements'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SectionForecastingRouteImport } from './routes/section-forecasting'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReadinessAuditRouteImport } from './routes/readiness-audit'
import { Route as QuarantinedStockRouteImport } from './routes/quarantined-stock'
import { Route as QrLabelsRouteImport } from './routes/qr-labels'
import { Route as PurchaseRequestsRouteImport } from './routes/purchase-requests'
import { Route as ProcurementFollowupRouteImport } from './routes/procurement-followup'
import { Route as MaintenanceCalibrationRouteImport } from './routes/maintenance-calibration'
import { Route as LowStockReorderRouteImport } from './routes/low-stock-reorder'
import { Route as InventoryMasterRouteImport } from './routes/inventory-master'
import { Route as ExpiryFefoRouteImport } from './routes/expiry-fefo'
import { Route as ExpiredWastedStockRouteImport } from './routes/expired-wasted-stock'
import { Route as EquipmentRegisterRouteImport } from './routes/equipment-register'
import { Route as DurablesRegisterRouteImport } from './routes/durables-register'
import { Route as DataQualityReviewRouteImport } from './routes/data-quality-review'
import { Route as CriticalActionsRouteImport } from './routes/critical-actions'
import { Route as BatchRegisterRouteImport } from './routes/batch-register'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as AcceptanceTestingRouteImport } from './routes/acceptance-testing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSectionIdRouteImport } from './routes/section.$sectionId'
import { Route as RTypeIdRouteImport } from './routes/r.$type.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyStatusRoute = SupplyStatusRouteImport.update({
  id: '/supply-status',
  path: '/supply-status',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMovementsRoute = StockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionForecastingRoute = SectionForecastingRouteImport.update({
  id: '/section-forecasting',
  path: '/section-forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessAuditRoute = ReadinessAuditRouteImport.update({
  id: '/readiness-audit',
  path: '/readiness-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarantinedStockRoute = QuarantinedStockRouteImport.update({
  id: '/quarantined-stock',
  path: '/quarantined-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const QrLabelsRoute = QrLabelsRouteImport.update({
  id: '/qr-labels',
  path: '/qr-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsRoute = PurchaseRequestsRouteImport.update({
  id: '/purchase-requests',
  path: '/purchase-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementFollowupRoute = ProcurementFollowupRouteImport.update({
  id: '/procurement-followup',
  path: '/procurement-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceCalibrationRoute = MaintenanceCalibrationRouteImport.update({
  id: '/maintenance-calibration',
  path: '/maintenance-calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const LowStockReorderRoute = LowStockReorderRouteImport.update({
  id: '/low-stock-reorder',
  path: '/low-stock-reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryMasterRoute = InventoryMasterRouteImport.update({
  id: '/inventory-master',
  path: '/inventory-master',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryFefoRoute = ExpiryFefoRouteImport.update({
  id: '/expiry-fefo',
  path: '/expiry-fefo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiredWastedStockRoute = ExpiredWastedStockRouteImport.update({
  id: '/expired-wasted-stock',
  path: '/expired-wasted-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRegisterRoute = EquipmentRegisterRouteImport.update({
  id: '/equipment-register',
  path: '/equipment-register',
  getParentRoute: () => rootRouteImport,
} as any)
const DurablesRegisterRoute = DurablesRegisterRouteImport.update({
  id: '/durables-register',
  path: '/durables-register',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityReviewRoute = DataQualityReviewRouteImport.update({
  id: '/data-quality-review',
  path: '/data-quality-review',
  getParentRoute: () => rootRouteImport,
} as any)
const CriticalActionsRoute = CriticalActionsRouteImport.update({
  id: '/critical-actions',
  path: '/critical-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRegisterRoute = BatchRegisterRouteImport.update({
  id: '/batch-register',
  path: '/batch-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptanceTestingRoute = AcceptanceTestingRouteImport.update({
  id: '/acceptance-testing',
  path: '/acceptance-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionIdRoute = SectionSectionIdRouteImport.update({
  id: '/section/$sectionId',
  path: '/section/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RTypeIdRoute = RTypeIdRouteImport.update({
  id: '/r/$type/$id',
  path: '/r/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptance-testing': typeof AcceptanceTestingRoute
  '/audit-trail': typeof AuditTrailRoute
  '/batch-register': typeof BatchRegisterRoute
  '/critical-actions': typeof CriticalActionsRoute
  '/data-quality-review': typeof DataQualityReviewRoute
  '/durables-register': typeof DurablesRegisterRoute
  '/equipment-register': typeof EquipmentRegisterRoute
  '/expired-wasted-stock': typeof ExpiredWastedStockRoute
  '/expiry-fefo': typeof ExpiryFefoRoute
  '/inventory-master': typeof InventoryMasterRoute
  '/low-stock-reorder': typeof LowStockReorderRoute
  '/maintenance-calibration': typeof MaintenanceCalibrationRoute
  '/procurement-followup': typeof ProcurementFollowupRoute
  '/purchase-requests': typeof PurchaseRequestsRoute
  '/qr-labels': typeof QrLabelsRoute
  '/quarantined-stock': typeof QuarantinedStockRoute
  '/readiness-audit': typeof ReadinessAuditRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/section-forecasting': typeof SectionForecastingRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/supply-status': typeof SupplyStatusRoute
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/r/$type/$id': typeof RTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptance-testing': typeof AcceptanceTestingRoute
  '/audit-trail': typeof AuditTrailRoute
  '/batch-register': typeof BatchRegisterRoute
  '/critical-actions': typeof CriticalActionsRoute
  '/data-quality-review': typeof DataQualityReviewRoute
  '/durables-register': typeof DurablesRegisterRoute
  '/equipment-register': typeof EquipmentRegisterRoute
  '/expired-wasted-stock': typeof ExpiredWastedStockRoute
  '/expiry-fefo': typeof ExpiryFefoRoute
  '/inventory-master': typeof InventoryMasterRoute
  '/low-stock-reorder': typeof LowStockReorderRoute
  '/maintenance-calibration': typeof MaintenanceCalibrationRoute
  '/procurement-followup': typeof ProcurementFollowupRoute
  '/purchase-requests': typeof PurchaseRequestsRoute
  '/qr-labels': typeof QrLabelsRoute
  '/quarantined-stock': typeof QuarantinedStockRoute
  '/readiness-audit': typeof ReadinessAuditRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/section-forecasting': typeof SectionForecastingRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/supply-status': typeof SupplyStatusRoute
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/r/$type/$id': typeof RTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptance-testing': typeof AcceptanceTestingRoute
  '/audit-trail': typeof AuditTrailRoute
  '/batch-register': typeof BatchRegisterRoute
  '/critical-actions': typeof CriticalActionsRoute
  '/data-quality-review': typeof DataQualityReviewRoute
  '/durables-register': typeof DurablesRegisterRoute
  '/equipment-register': typeof EquipmentRegisterRoute
  '/expired-wasted-stock': typeof ExpiredWastedStockRoute
  '/expiry-fefo': typeof ExpiryFefoRoute
  '/inventory-master': typeof InventoryMasterRoute
  '/low-stock-reorder': typeof LowStockReorderRoute
  '/maintenance-calibration': typeof MaintenanceCalibrationRoute
  '/procurement-followup': typeof ProcurementFollowupRoute
  '/purchase-requests': typeof PurchaseRequestsRoute
  '/qr-labels': typeof QrLabelsRoute
  '/quarantined-stock': typeof QuarantinedStockRoute
  '/readiness-audit': typeof ReadinessAuditRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/section-forecasting': typeof SectionForecastingRoute
  '/settings': typeof SettingsRoute
  '/stock-movements': typeof StockMovementsRoute
  '/supply-status': typeof SupplyStatusRoute
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/r/$type/$id': typeof RTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptance-testing'
    | '/audit-trail'
    | '/batch-register'
    | '/critical-actions'
    | '/data-quality-review'
    | '/durables-register'
    | '/equipment-register'
    | '/expired-wasted-stock'
    | '/expiry-fefo'
    | '/inventory-master'
    | '/low-stock-reorder'
    | '/maintenance-calibration'
    | '/procurement-followup'
    | '/purchase-requests'
    | '/qr-labels'
    | '/quarantined-stock'
    | '/readiness-audit'
    | '/reports'
    | '/scan'
    | '/section-forecasting'
    | '/settings'
    | '/stock-movements'
    | '/supply-status'
    | '/training'
    | '/welcome'
    | '/section/$sectionId'
    | '/r/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptance-testing'
    | '/audit-trail'
    | '/batch-register'
    | '/critical-actions'
    | '/data-quality-review'
    | '/durables-register'
    | '/equipment-register'
    | '/expired-wasted-stock'
    | '/expiry-fefo'
    | '/inventory-master'
    | '/low-stock-reorder'
    | '/maintenance-calibration'
    | '/procurement-followup'
    | '/purchase-requests'
    | '/qr-labels'
    | '/quarantined-stock'
    | '/readiness-audit'
    | '/reports'
    | '/scan'
    | '/section-forecasting'
    | '/settings'
    | '/stock-movements'
    | '/supply-status'
    | '/training'
    | '/welcome'
    | '/section/$sectionId'
    | '/r/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/acceptance-testing'
    | '/audit-trail'
    | '/batch-register'
    | '/critical-actions'
    | '/data-quality-review'
    | '/durables-register'
    | '/equipment-register'
    | '/expired-wasted-stock'
    | '/expiry-fefo'
    | '/inventory-master'
    | '/low-stock-reorder'
    | '/maintenance-calibration'
    | '/procurement-followup'
    | '/purchase-requests'
    | '/qr-labels'
    | '/quarantined-stock'
    | '/readiness-audit'
    | '/reports'
    | '/scan'
    | '/section-forecasting'
    | '/settings'
    | '/stock-movements'
    | '/supply-status'
    | '/training'
    | '/welcome'
    | '/section/$sectionId'
    | '/r/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptanceTestingRoute: typeof AcceptanceTestingRoute
  AuditTrailRoute: typeof AuditTrailRoute
  BatchRegisterRoute: typeof BatchRegisterRoute
  CriticalActionsRoute: typeof CriticalActionsRoute
  DataQualityReviewRoute: typeof DataQualityReviewRoute
  DurablesRegisterRoute: typeof DurablesRegisterRoute
  EquipmentRegisterRoute: typeof EquipmentRegisterRoute
  ExpiredWastedStockRoute: typeof ExpiredWastedStockRoute
  ExpiryFefoRoute: typeof ExpiryFefoRoute
  InventoryMasterRoute: typeof InventoryMasterRoute
  LowStockReorderRoute: typeof LowStockReorderRoute
  MaintenanceCalibrationRoute: typeof MaintenanceCalibrationRoute
  ProcurementFollowupRoute: typeof ProcurementFollowupRoute
  PurchaseRequestsRoute: typeof PurchaseRequestsRoute
  QrLabelsRoute: typeof QrLabelsRoute
  QuarantinedStockRoute: typeof QuarantinedStockRoute
  ReadinessAuditRoute: typeof ReadinessAuditRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  SectionForecastingRoute: typeof SectionForecastingRoute
  SettingsRoute: typeof SettingsRoute
  StockMovementsRoute: typeof StockMovementsRoute
  SupplyStatusRoute: typeof SupplyStatusRoute
  TrainingRoute: typeof TrainingRoute
  WelcomeRoute: typeof WelcomeRoute
  SectionSectionIdRoute: typeof SectionSectionIdRoute
  RTypeIdRoute: typeof RTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-status': {
      id: '/supply-status'
      path: '/supply-status'
      fullPath: '/supply-status'
      preLoaderRoute: typeof SupplyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-movements': {
      id: '/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof StockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section-forecasting': {
      id: '/section-forecasting'
      path: '/section-forecasting'
      fullPath: '/section-forecasting'
      preLoaderRoute: typeof SectionForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness-audit': {
      id: '/readiness-audit'
      path: '/readiness-audit'
      fullPath: '/readiness-audit'
      preLoaderRoute: typeof ReadinessAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarantined-stock': {
      id: '/quarantined-stock'
      path: '/quarantined-stock'
      fullPath: '/quarantined-stock'
      preLoaderRoute: typeof QuarantinedStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-labels': {
      id: '/qr-labels'
      path: '/qr-labels'
      fullPath: '/qr-labels'
      preLoaderRoute: typeof QrLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests': {
      id: '/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/purchase-requests'
      preLoaderRoute: typeof PurchaseRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-followup': {
      id: '/procurement-followup'
      path: '/procurement-followup'
      fullPath: '/procurement-followup'
      preLoaderRoute: typeof ProcurementFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-calibration': {
      id: '/maintenance-calibration'
      path: '/maintenance-calibration'
      fullPath: '/maintenance-calibration'
      preLoaderRoute: typeof MaintenanceCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/low-stock-reorder': {
      id: '/low-stock-reorder'
      path: '/low-stock-reorder'
      fullPath: '/low-stock-reorder'
      preLoaderRoute: typeof LowStockReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-master': {
      id: '/inventory-master'
      path: '/inventory-master'
      fullPath: '/inventory-master'
      preLoaderRoute: typeof InventoryMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry-fefo': {
      id: '/expiry-fefo'
      path: '/expiry-fefo'
      fullPath: '/expiry-fefo'
      preLoaderRoute: typeof ExpiryFefoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expired-wasted-stock': {
      id: '/expired-wasted-stock'
      path: '/expired-wasted-stock'
      fullPath: '/expired-wasted-stock'
      preLoaderRoute: typeof ExpiredWastedStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-register': {
      id: '/equipment-register'
      path: '/equipment-register'
      fullPath: '/equipment-register'
      preLoaderRoute: typeof EquipmentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/durables-register': {
      id: '/durables-register'
      path: '/durables-register'
      fullPath: '/durables-register'
      preLoaderRoute: typeof DurablesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality-review': {
      id: '/data-quality-review'
      path: '/data-quality-review'
      fullPath: '/data-quality-review'
      preLoaderRoute: typeof DataQualityReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critical-actions': {
      id: '/critical-actions'
      path: '/critical-actions'
      fullPath: '/critical-actions'
      preLoaderRoute: typeof CriticalActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-register': {
      id: '/batch-register'
      path: '/batch-register'
      fullPath: '/batch-register'
      preLoaderRoute: typeof BatchRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptance-testing': {
      id: '/acceptance-testing'
      path: '/acceptance-testing'
      fullPath: '/acceptance-testing'
      preLoaderRoute: typeof AcceptanceTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$sectionId': {
      id: '/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/section/$sectionId'
      preLoaderRoute: typeof SectionSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$type/$id': {
      id: '/r/$type/$id'
      path: '/r/$type/$id'
      fullPath: '/r/$type/$id'
      preLoaderRoute: typeof RTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptanceTestingRoute: AcceptanceTestingRoute,
  AuditTrailRoute: AuditTrailRoute,
  BatchRegisterRoute: BatchRegisterRoute,
  CriticalActionsRoute: CriticalActionsRoute,
  DataQualityReviewRoute: DataQualityReviewRoute,
  DurablesRegisterRoute: DurablesRegisterRoute,
  EquipmentRegisterRoute: EquipmentRegisterRoute,
  ExpiredWastedStockRoute: ExpiredWastedStockRoute,
  ExpiryFefoRoute: ExpiryFefoRoute,
  InventoryMasterRoute: InventoryMasterRoute,
  LowStockReorderRoute: LowStockReorderRoute,
  MaintenanceCalibrationRoute: MaintenanceCalibrationRoute,
  ProcurementFollowupRoute: ProcurementFollowupRoute,
  PurchaseRequestsRoute: PurchaseRequestsRoute,
  QrLabelsRoute: QrLabelsRoute,
  QuarantinedStockRoute: QuarantinedStockRoute,
  ReadinessAuditRoute: ReadinessAuditRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  SectionForecastingRoute: SectionForecastingRoute,
  SettingsRoute: SettingsRoute,
  StockMovementsRoute: StockMovementsRoute,
  SupplyStatusRoute: SupplyStatusRoute,
  TrainingRoute: TrainingRoute,
  WelcomeRoute: WelcomeRoute,
  SectionSectionIdRoute: SectionSectionIdRoute,
  RTypeIdRoute: RTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
